#! /usr/bin/env bash
#
# Print list of files that would be generated by the passed README files.

set -eou pipefail

for readme in "$@"; do
    ./scripts/generate_from_readme.awk -v list=1 "${readme}"
done
